version: '3.8'
services:
  gateway_test:
    container_name: ntfgb_gateway_test
    image: ntfgb_gateway_test_image
    depends_on:
      - socket_test
    build:
      context: ./src/gateway
      dockerfile: Dockerfile
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - GATEWAY_PORT=${GATEWAY_PORT}
      - SOCKET_SUBGRAPH_PORT=${SOCKET_SUBGRAPH_PORT}
      - MONGO_URI=${MONGO_URI}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED}
      - NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED}
    networks:
      - "ntfgb_test"

  socket_test:
    container_name: ntfgb_socket_test
    image: ntfgb_socket_test_image
    depends_on:
      - mongo_test
    build:
      context: ./src/subgraphs/socket
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - OPEN_CHARGE_MAP_API_KEY=${OPEN_CHARGE_MAP_API_KEY}
      - SOCKET_SUBGRAPH_PORT=${SOCKET_SUBGRAPH_PORT}
      - MONGO_URI=${MONGO_URI}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED}
      - NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED}
    networks:
      - "ntfgb_test"

  mongo_test:
    container_name: ntfgb_mongodb_test
    image: mongo:6
    depends_on:
      - mongo_test_seed
    ports:
      - "27018:27017"
    networks:
      - "ntfgb_test"

  mongo_test_seed:
    container_name: ntfgb_mongodb_test_seed
    image: ntfgb_mongodb_test_seed_image
    build:
      context: ./src/database-test
      dockerfile: Dockerfile
      args:
        - MONGO_URI=$MONGO_URI
    networks:
      - "ntfgb_test"

networks:
  "ntfgb_test":
