version: '3.8'
services:
  gateway-test:
    container_name: ntfgb-gateway-test
    image: ntfgb-gateway-test-image
    depends_on:
      - socket-test
    build:
      context: ./src/gateway
      dockerfile: Dockerfile
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - GATEWAY_PORT=${GATEWAY_PORT}
      - SOCKET_SUBGRAPH_PORT=${SOCKET_SUBGRAPH_PORT}
      - MONGO_URI=${MONGO_URI}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED}
      - NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED}
    networks:
      - ntfgb-test

  socket-test:
    container_name: ntfgb-socket-test
    image: ntfgb-socket-test-image
    depends_on:
      - mongo-test
    build:
      context: ./src/subgraphs/socket
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - OPEN_CHARGE_MAP_API_KEY=${OPEN_CHARGE_MAP_API_KEY}
      - SOCKET_SUBGRAPH_PORT=${SOCKET_SUBGRAPH_PORT}
      - MONGO_URI=${MONGO_URI}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED}
      - NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED}
    networks:
      - ntfgb-test

  mongo-test:
    container_name: ntfgb-mongodb-test
    image: ntfgb-mongodb-test-image
    build:
      context: ./src/database-test
      dockerfile: Dockerfile
    networks:
      - ntfgb-test

networks:
  ntfgb-test:
