version: '3.8'

services:

  gateway:
    container_name: ntfgb-gateway
    image: ntfgb-gateway-image
    depends_on:
      - socket
    build:
      context: ./src/gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  socket:
    container_name: ntfgb-socket
    image: ntfgb-socket-image
    depends_on:
      - mongo
    build:
      context: ./src/subgraphs/socket
      dockerfile: Dockerfile
    environment:
        - OPEN_CHARGE_MAP_API_KEY=<Your Key Goes Here>
        - MONGO_URI=mongodb://mongo:27017/ntfgb

  mongo:
    build:
      context: ./src/database
      dockerfile: Dockerfile
    ports:
      - '27017:27017'
    container_name: ntfgb-mongodb
    image: ntfgb-mongodb-image