version: '3.8'
services:
  gateway:
    container_name: ntfgb-gateway
    image: ntfgb-gateway-image
    depends_on:
      - socket
    build:
      context: ./src/gateway
      dockerfile: Dockerfile
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - GATEWAY_PORT=${GATEWAY_PORT}
      - SOCKET_SUBGRAPH_PORT=${SOCKET_SUBGRAPH_PORT}
      - MONGO_URI=${MONGO_URI}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED}
      - NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED}
    networks:
      - ntfgb

  socket:
    container_name: ntfgb-socket
    image: ntfgb-socket-image
    depends_on:
      - mongo
    build:
      context: ./src/subgraphs/socket
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - OPEN_CHARGE_MAP_API_KEY=${OPEN_CHARGE_MAP_API_KEY}
      - SOCKET_SUBGRAPH_PORT=${SOCKET_SUBGRAPH_PORT}
      - MONGO_URI=${MONGO_URI}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED}
      - NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED}
    networks:
      - ntfgb

  mongo:
    container_name: ntfgb-mongodb
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - ntfgb

volumes:
  mongo-data:

networks:
  ntfgb:
